name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    name: Tests (${{ matrix.browser }})

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      # Install basic python requirements
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt

      # Checks storage
      - name: Cache Playwright Browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('requirements.txt') }}

      # Install OS dependencies and fill browser cache if empty
      - name: Install Playwright system dependencies
        run: python -m playwright install --with-deps ${{ matrix.browser }}

      # Enable tracing
      - name: Run tests
        run: pytest --browser ${{ matrix.browser }} --tracing retain-on-failure

      # Upload both traces and screenshots only if failure occurs
      - name: Upload Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-artifacts-${{ matrix.browser }}
          path: |
            test-results/
            screenshots/
          if-no-files-found: ignore
